apiVersion: v1
kind: Pod
metadata:
  name: backup-tool
  labels:
    app: backup-tool
spec:
  containers:
    - name: backup-tool
      image: 10.0.1.104:5000/backup-tool:latest
      imagePullPolicy: Always
      args: ["sleep", "infinity"]
      envFrom:
        - configMapRef:
            name: backup-env-config
      volumeMounts:
        - name: data
          mountPath: /uploads
        - name: backups
          mountPath: /backups
        - name: file-config
          mountPath: /etc/backup-tool/backup.conf
          subPath: backup.conf
          readOnly: true
        - name: secret-passphrase
          mountPath: /etc/backup-tool/secrets
          readOnly: true
  volumes:
    - name: data
      emptyDir: {}
    - name: backups
      emptyDir: {}
    - name: file-config
      configMap:
        name: backup-file-config
    - name: secret-passphrase
      secret:
        secretName: backup-passphrase
        defaultMode: 0400
