apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pvc-test
spec:
  containers:
    - name: test
      image: 10.0.1.104:5000/backup-tool:latest
      args: ["sleep", "infinity"]
      volumeMounts:
        - name: data
          mountPath: /backups
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: backup-archive-dynamic-pvc
